### ISSUE TITLE
Import arXiv

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/MaRDIRoadmap#34]
**Describe the issue**
see https://github.com/MaRDI4NFDI/portal-compose/issues/338

- [ ] latest dataset from https://sigmathling.kwarc.info/resources/ar5iv-dataset-2024/
- [ ] Set up local cache
```
# delete after first run
  unzip:
    image: dockerqa/unzip
    volumes:
      - /hdd/datasets/arxiv/dataset-arxmliv-2024/data:/unzip:ro
      - arxiv-data:/data
    command:
      - '-d /data *.zip'
  httpd:
    image: httpd:2.4
    restart: always
    volumes:
      - /hdd/htdocs:/usr/local/apache2/htdocs/:ro
      - arxiv-data:/arxiv:ro
      - ./secret/apache.htpasswd:/usr/local/apache2/.htpasswd:ro
      - ./config/apache.httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
